-- CONECTADO COMO EL USUARIO ADMIN

CREATE USER VideojuegosDB IDENTIFIED BY ev_parcial1;

ALTER USER VideojuegosDB DEFAULT TABLESPACE DATA
              QUOTA UNLIMITED ON DATA;

ALTER USER VideojuegosDB TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO VideojuegosDB;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO VideojuegosDB;