

CREATE OR REPLACE FUNCTION FN_CATEGORIZAR_CLIENTE(id_cliente IN CLIENTE.CLIENTE_ID%TYPE) 
RETURN VARCHAR2
IS 
V_CATEGORIA VARCHAR2(20);
V_TOTAL NUMBER;
BEGIN

    SELECT COUNT(DV.VENTA_ID)
    INTO V_TOTAL
    FROM DETALLE_VENTA DV
    JOIN VENTA V ON (V.VENTA_ID = DV.VENTA_ID)
    JOIN CLIENTE C ON (C.CLIENTE_ID = V.CLIENTE_ID)

    WHERE C.CLIENTE_ID = id_cliente;
    
    IF V_TOTAL > 1 THEN
        V_CATEGORIA := 'CLIENTE FRECUENTE';
    ELSE
        V_CATEGORIA := 'CLIENTE OCASIONAL';
    END IF;

    RETURN V_CATEGORIA;

END;

/

SELECT fn_categorizar_cliente(1) AS CATEGORIA FROM dual;