CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_STOCK
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW -- <--- ESTO LO DEFINE COMO NIVEL DE FILA
BEGIN
    UPDATE VIDEOJUEGO
    SET STOCK = STOCK - :NEW.CANTIDAD
    WHERE VIDEOJUEGO_ID = :NEW.VIDEOJUEGO_ID;
END;