--Record almacinar cliente
CREATE OR REPLACE TYPE REC_CLIENTE AS OBJECT(
    CLIENTE_ID NUMBER,
    NOMBRE VARCHAR2(50),
    APELLIDO VARCHAR2(50),
    EMAIL VARCHAR2(100),
    FECHA_REGISTRO DATE,
    TELEFONO VARCHAR2(15)
);