CREATE USER VideojuegosDB IDENTIFIED BY Chilegames12;

ALTER USER VideojuegosDB DEFAULT TABLESPACE DATA
QUOTA UNLIMITED ON DATA;

ALTER USER VideojuegosDB TEMPORARY TABLESPACE TEMP;

GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO VideojuegosDB;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO VideojuegosDB;